### ISSUE TITLE
KeepaAPI.sendRequest is private

### ISSUE THREAD

**Issue by ambarisch** [keepacom/api_backend#1]
This method `KeepaAPI.sendRequest` is used in the example on ReadMe page, but is not accessible (private). While `sendRequestWithRetry` is public, there are some cases where you may not want to retry.

Is `sendRequest` made private for a specific reason? If yes, is there any other solution?

**Comment by keepacom** [comment]
Thanks for pointing that out. We changed it to public and released version 1.12, available via Maven and GitHub.

**Comment by ambarisch** [comment]
Hi,

Thanks for a quick resolution. A similar issue with `class ProductAnalyzer`, which earlier was public, but now only has package level access.

Thanks,

-ambarish

**Comment by keepacom** [comment]
Fixed with 1.13. Thanks!
