### ISSUE TITLE
Cannot find classes all of sudden

### ISSUE THREAD

**Issue by shaykh-salman** [keepacom/api_backend#11]
Cannot download dependencies all of sudden. It was working fine, all of sudden cannot find API for KeepaAPI

**Comment by keepacom** [comment]
Which version did you add? Any error messages?

```
<repository>
	<id>Keepa</id>
	<name>Keepa Repository</name>
	<url>https://keepa.com/maven/</url>
</repository>

<dependency>
	<groupId>com.keepa.api</groupId>
	<artifactId>backend</artifactId>
	<version>1.36</version>
</dependency>
```

**Comment by shaykh-salman** [comment]
Using, LATEST as version, it was same before.

**Comment by keepacom** [comment]
We checked and found no issues. Can you provide more details?
