### ISSUE TITLE
RATING, USED_ACCEPTABLE KEYS not working.

### ISSUE THREAD

**Issue by ZenonH** [keepacom/api_backend#12]
RATING, USED_ACCEPTABLE KEYS not working.

This is my test code:
# for a list of ASIN_NOS and
# a user entered date
# get historical prices for USED, USED_ACCEPTABLE_SHIPPING, RATING for that date
# and get current prices for USED, USED_ACCEPTABLE_SHIPPING, and TRADE_IN

import sys
import keepaAPI
import numpy
from datetime import datetime, date
import csv

#args=sys.argv[1:3]
#access_key=sys.argv[1]
#ASIN_no=sys.argv[2]
#userDate=sys.argv[3]

access_key = 'enter your key here'

#test data
keys=['USED','USED_ACCEPTABLE_SHIPPING','RATING','TRADE_IN']
ASIN_NOS= ['128405330X','321924592','1455753580','130563182X','133545172','393936937','321984579','1305105400','321809246','1450434320','133753980','1285196147','B01CMY8SYG','1118133579','321948912','1464167524','895829479','393936384','128516590X','1457659956','1305105427','007802899X','1449689744','78952719','78119065','1118147391','131359584','321944518','321928091','1464167524','878939660','1305633652','887276709']
user_date='2017-12-01'
''
#initialize Keepa API
api = keepaAPI.API(access_key)

#open null file for writing
with open("results.csv","w", newline = '') as f:
    f.write(('ASIN, Title, Key, Current Date, Current Price, Pasr Date, Past Price'))
    writer=csv.writer(f)
    writer.writerow('')

products = api.ProductQuery(ASIN_NOS)

for product in products:
    asin = product['asin']
    title = product['title']

    # process selected keys
    for k in range(len(keys)):

        ky = keys[k]

        past_price = 0
        current_price = 0

        # Access key price history and associated time data
        try:
            price_data = product['data'][keys[k]]
            time_periods = product['data'][keys[k] + '_time']
        except:
            past_price = 'na'
            current_price  = 'na'

        if past_price != 'na':

            # get historical prices
            for j in range(len(price_data)-1):
                past_date = datetime.strftime(time_periods[j],"%Y-%m-%d")
                if past_date >= user_date and past_price == 0:
                    past_price = price_data[j]
                    break

            for j in range(len(price_data)-1, 0, -1):

            #for j in range(len(price_data)-1):
                current_price = price_data[j]
                if current_price > 0:
                    current_date = time_periods[j]
                    break

        with open('results.csv','a', newline='') as f:
            writer=csv.writer(f)
            writer.writerow([asin, title, ky, current_date,
                             current_price, past_date, past_price])

print("Done")

Thanks in advance for your time.

**Comment by keepacom** [comment]
For access to the Rating history you have to either use the rating or offers parameter.
For access to the Used Acceptable history you have to use the offers parameter.

See documentation of the [product request](https://discuss.keepa.com/t/request-products/110?u=keepa).

**Comment by ZenonH** [comment]
Thanks for your prompt response.
