### ISSUE TITLE
Does 1.47 include the 6th March changes?

### ISSUE THREAD

**Issue by ttimbul** [keepacom/api_backend#13]
See https://keepa.com/?fbclid=IwAR33eNt_72ZwEZlF91MLUTmJJzk47KQEsnFaZpgx_hzRnT2peL1dJ1wZSvU#!discuss/t/upcoming-keepa-api-changes-march-6th/9366

Are these changes incorporated? I don't see `salesRankReference` for example.

**Comment by keepacom** [comment]
Just released 1.49 does include all changes.
