### ISSUE TITLE
Implement method KeepaAPI#sendRequestWithRetry

### ISSUE THREAD

**Issue by fantnk** [keepacom/api_backend#18]
There is no easy way to implement retry with custom timeouts now. It seems useful to implement new method `sendRequestWithRetry(Request r, int connectTimeout, int readTimeout)` corresponding to already implemented `sendRequest(Request r, int connectTimeout, int readTimeout)`.

**Comment by keepacom** [comment]
Thank for your suggestion. The new method is now available in version 1.77.
