### ISSUE TITLE
stockCsv variable of offer objects never set

### ISSUE THREAD

**Issue by abu-siddique** [keepacom/api_backend#20]
I am using java backend API to get the stats of products.  I have set offer parameter 20 in the request object. Before hitting the API i have checked offer section of keepa UI where i can see stock related info(like stock , sold, sold last 30 days stock history) but in the response api i dont see those info. Also in the offer object you have a field called stockCsv but it was never descried in your [documentation](https://keepa.com/#!discuss/t/marketplace-offer-object/807)

**Comment by keepacom** [comment]
Stock data is not accessible through our API.
