### ISSUE TITLE
TrackingRequest notificationType field wrong type

### ISSUE THREAD

**Issue by SurfVaporizer** [keepacom/api_backend#3]
Hello guys, I noticed that notificationType field has a type of boolean[] but in description the link is reffer to NotificationType.

Should the variable be with type NotificationType[] ????

```
public enum NotificationType {
		EMAIL, TWITTER, FACEBOOK_NOTIFICATION, BROWSER, FACEBOOK_MESSENGER_BOT, API, MOBILE_APP;
		public static final NotificationType[] values = NotificationType.values();

	}

```

```
/**
	 * Determines through which channels we will send notifications.<br>
	 * Uses NotificationType indexing {@link NotificationType}. True means the channel will be used.
	 */
	public boolean[] notificationType;
```

I got next error:

```
"status": "REQUEST_REJECTED",
  "error": {
    "type": "invalidParameter",
    "message": "The queryJSON is of invalid format.",
    "details": "notificationType is of invalid length"
  }
```

**Comment by keepacom** [comment]
Hi, 
Sorry this is confusing. We will improve the JavaDoc with the next version. From the API [documentation](https://keepa.com/#!discuss/t/tracking-creation-object/2068):

> Must be a boolean array with the length of the NotificationType enum (= 7). Determines through which channels we will send notifications. Uses NotificationType indexing. True means the channel will be used.
> Important: 
> Our Tracking API currently only supports notifications through push webhooks or API pull request. Other channels will follow soon.
> Example: Only notify via API: [ false, false, false, false, false, true, false ]

So for Java:
`boolean[] notificationType = new boolean[Tracking.NotificationType.values.length];`
`notificationType[Tracking.NotificationType.API.ordinal()] = true;`

**Comment by SurfVaporizer** [comment]
Thanks a lot and good luck.

**Comment by SurfVaporizer** [comment]
@keepacom Thanks for response.

I've tried push your solution but still getting error:

```
"error": {
    "type": "invalidParameter",
    "message": "The queryJSON is of invalid format.",
    "details": "notificationType is of invalid length"
  }
```

Screen from TrackingRequest dump. 

![image](https://cloud.githubusercontent.com/assets/2387482/21077474/6f16dda8-bf1a-11e6-840e-15e4b9bba05e.png)

**Comment by keepacom** [comment]
Thanks for the feedback. Our invalid parameter check makes a mistake. We will fix this asap, in the meanwhile you can just set it to "null", our system will then automatically set it to only alert through the API.
