### ISSUE TITLE
"LATEST" is not a valid version

### ISSUE THREAD

**Issue by ttimbul** [keepacom/api_backend#4]
"LATEST" doesn't resolve. Specifying <version>1.22</version> works.

**Comment by keepacom** [comment]
Hello,

We sorry that is not working for you.

We tried two ways (CLI and IntelliJ) to reproduce it, but its working for us:

> rm -rf ~/.m2/ && mvn dependency:get -DrepoUrl=https://keepa.com/maven/ -DgroupId=com.keepa.api -DartifactId=backend -Dversion=LATEST

> [INFO] Scanning for projects...
> Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
> ...
> Downloading: https://keepa.com/maven/com/keepa/api/backend/maven-metadata.xml
> Downloaded: https://keepa.com/maven/com/keepa/api/backend/maven-metadata.xml (718 B at 3.4 KB/sec)
> Downloading: https://keepa.com/maven/com/keepa/api/backend/1.22/backend-1.22.jar
> Downloaded: https://keepa.com/maven/com/keepa/api/backend/1.22/backend-1.22.jar (45 KB at 678.2 KB/sec)
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 9.242s
> [INFO] Finished at: Mon Sep 11 12:57:07 UTC 2017
> [INFO] Final Memory: 11M/58M
> [INFO] ------------------------------------------------------------------------

What client are you using / are you able to reproduce it?

**Comment by ttimbul** [comment]
Eclipse with Gradle.
Excerpt from build.gradle:

`repositories {`
`   ...`
`   maven { url 'https://keepa.com/maven/' }`
`   ...`
`}`
`dependencies {`
`   ...`
`   compile 'com.keepa.api:backend:LATEST'`
`   ...`
`}`

This produces "Could not resolve: com.keepa.api:backend:LATEST"

**Comment by keepacom** [comment]
hello,

please use 

> compile 'com.keepa.api:backend:latest.release'

and let me know if it worked

**Comment by ttimbul** [comment]
That appears to work!

**Comment by keepacom** [comment]
Wonderful !

Maybe makes also sense for you to tell the IDE to download every time (during build) the newest release feed from our server as mentioned here:

https://stackoverflow.com/questions/41672892/gradle-does-not-retrieve-latest-version-from-artifactory

You just have to add:

```
configurations.all {
    resolutionStrategy {
        cacheDynamicVersionsFor 0, 'seconds'
        cacheChangingModulesFor 0, 'seconds'
    }
}
```
to your build.gradle
