### ISSUE TITLE
"stat parameter invalid"

### ISSUE THREAD

**Issue by ttimbul** [keepacom/api_backend#5]
If I specify anything except 'null' for the "stat" parameter, I receive METHOD_NOT_ALLOWED and "stat parameter invalid". Apart from 45 below I have tried 10, 30, 60, 360.

Relevant code:

`int STAT = 45;`
`Integer OFFERS_TO_RETRIEVE = null;`
`Integer UPDATE_HOURS = -1;`
`boolean history = true;`
`Request.getProductRequest(amazonLocale, STAT, OFFERS_TO_RETRIEVE, UPDATE_HOURS, history, asins);`

**Comment by keepacom** [comment]
UPDATE_HOURS must be a positive value or 0. The default value is 1.

This method's stats parameter seems to be broken, thanks for reporting. We will release a fix asap, in the meanwhile you can use this method instead:
`getProductRequest(final AmazonLocale domainId, Long statsStartDate, Long statsEndDate, Integer offers, int update, boolean history, final String... asins)`

**Comment by ttimbul** [comment]
In the documentation it states that "update=-1" means never to retrieve fresh data?

I'll try the alternative method, thanks.

**Comment by keepacom** [comment]
You are correct of course, my mistake.

We just released version 1.23 to address the broken request. Thanks again for reporting.
