### ISSUE TITLE
No way to shutdown

### ISSUE THREAD

**Issue by ttimbul** [keepacom/api_backend#6]
There appears to be no way to shut down the KeepaAPI other than to call `System.exit()`.
Maybe the executor threads should be daemon threads, provide delegate methods to `shutdown()` and `shutdownNow()`, or provide getter access to each of the executors, whether public or protected to at least be able to subclass and add the functionality.

**Comment by keepacom** [comment]
We will add a shutdown method with the next release. Sorry for the late response.
